### ISSUE TITLE
The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by Bingo-1996** [JiehongLin/Self-DPDN#1]
Dear author, thanks for releasing the code! 
I have downloaded the pre-trained checkpoints, but I failed to evaluate both supervised and unsupervised models.
I'm wondering if there is a problem with the uploaded checkpoints? Can you give me some advice? thanks a lot!

![Screenshot from 2022-07-18 22-02-55](https://user-images.githubusercontent.com/69563953/179528962-2e81b8a0-b14c-48c8-b298-143b0f479686.png)
![Screenshot from 2022-07-18 22-04-08](https://user-images.githubusercontent.com/69563953/179529042-950bc4cb-84a4-41c8-a28e-ecaa26fa9cc0.png)

**Comment by Bingo-1996** [comment]
By the way, there is no version-0.2.5.6 for gorilla. Which one can I choose?

![Screenshot from 2022-07-18 22-23-08](https://user-images.githubusercontent.com/69563953/179532818-7f079e71-c842-4b35-aa14-2bd8c3ab8887.png)

**Comment by JiehongLin** [comment]
I have tested the code in my environment, and it could work successfully.  For the error,  it seems that there is no BN layer in pointnet++ backbone of the built model, although I have  set `bn=True` in the code `model/modules.py` (L243-L299). Maybe you could check whether any code w.r.t. BN is modified.

For gorilla-core, I guess versions between 0.2.5.x - 0.2.6.x maybe OK.

**Comment by Bingo-1996** [comment]
Maybe I have found the problem.  I use cuda11 not cuda10, and the pointnet2 module cannot be compiled on this platform, so I change this branch with the pointnet2 code provided by SGPA. But these two branches are different... 
I don't know how to change the pointnet2 branch to adapt to cuda11, can you give me some advice?

**Comment by JiehongLin** [comment]
Maybe you can try replacing the code in `setup.py` with the following one. 

```
import os
from setuptools import find_packages, setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension
import glob

this_dir = os.path.dirname(os.path.abspath(__file__))
_ext_src_root = os.path.join(this_dir, "_ext_src")
_ext_sources = glob.glob("{}/src/*.cpp".format(_ext_src_root)) + glob.glob(
    "{}/src/*.cu".format(_ext_src_root)
)
_ext_headers = glob.glob("{}/include/*".format(_ext_src_root))

setup(
    name='pointnet2',
    packages=find_packages(),
    ext_modules=[
        CUDAExtension(
            name="pointnet2._ext",
            sources=_ext_sources,
            extra_compile_args={
                "cxx": [],
                "nvcc": ["-O3", 
                "-DCUDA_HAS_FP16=1",
                "-D__CUDA_NO_HALF_OPERATORS__",
                "-D__CUDA_NO_HALF_CONVERSIONS__",
                "-D__CUDA_NO_HALF2_OPERATORS__",
            ]
            },
            include_dirs=[os.path.join(_ext_src_root, "include")],
        )
    ],
    cmdclass={
        'build_ext': BuildExtension
    }
)
```
