### ISSUE TITLE
Where is the 3D bounding box

### ISSUE THREAD

**Issue by AFESDTTM** [JiehongLin/Self-DPDN#10]
Hello author：
                     I would like to ask how the 3D bounding box in the results was made, do you need any other code, and where can I find it if needed. for example

![image](https://github.com/JiehongLin/Self-DPDN/assets/106895081/7959ec95-7f30-46c1-be4b-24484f812234)

**Comment by JiehongLin** [comment]
You may refer to the [link](https://github.com/hughw19/NOCS_CVPR2019/blob/dd58dbf68feede04c3d7bbafeb9212af1a43422f/utils.py#L2784).

**Comment by AFESDTTM** [comment]
Thank
