### ISSUE TITLE
Evaluation Metric

### ISSUE THREAD

**Issue by taeyeopl** [JiehongLin/Self-DPDN#11]
There exist small mistakes in the original evaluation source code of NOCS. I recommend changing to revised metrics (https://github.com/swords123/SSC-6D#note).

https://github.com/JiehongLin/Self-DPDN/blob/5305f7b34a12786fec902a6e57f83a393e24e902/utils/evaluation_utils.py#L124-L127
```
        # new
        bbox_1_max = np.amax(bbox_3d_1, axis=1)
        bbox_1_min = np.amin(bbox_3d_1, axis=1)
        bbox_2_max = np.amax(bbox_3d_2, axis=1)
        bbox_2_min = np.amin(bbox_3d_2, axis=1)
```

**Comment by JiehongLin** [comment]
Thank you for the suggestion. I have noticed this issue and used the evaluation code provided by [CATRE](https://github.com/THU-DA-6D-Pose-Group/CATRE) in our latest paper of [VI-Net](https://github.com/JiehongLin/VI-Net).

**Comment by taeyeopl** [comment]
Thanks for the code and for sharing recent work!
