### ISSUE TITLE
How can I obtain the mug_meta.pkl and other .pkl documents?

### ISSUE THREAD

**Issue by Ironman6666** [JiehongLin/Self-DPDN#2]
I am trying to run the data_processing.py, but it notices me that "FileNotFoundError: [Errno 2] No such file or directory: '/PycharmProject/DPDN/data/obj_models/mug_meta.pkl'
"
I can't find the file mug_meta.pkl in data/obj_models.Where can I get mug_meta.pkl and other .pkl documents? Or How can I generate it?

Thank you!

**Comment by JiehongLin** [comment]
I have updated the code, and the .pkl documents are not needed. You could try the new code.

**Comment by Ironman6666** [comment]
Thank you for your reply and thanks so much o(*￣▽￣*)ブ

> I have updated the code, and the .pkl documents are not needed. You could try the new code.

**Comment by Ironman6666** [comment]
> I have updated the code, and the .pkl documents are not needed. You could try the new code.

I am sorry that I probably have another small problem.I have updated the data_processing.py and run it again. But when the function annotate_real_train(data_dir) was excuted, it noticed me that in line 109 
" bbox_file = os.path.join(OBJ_MODEL_DIR, 'real_'+subset, model_id+'.txt')
TypeError: must be str, not NoneType".
I read the code carefully and probably find the reason.As the data storage you said,maybe are there should be 'real_train' in line 109 and not the 'real_'?And I'm  curious about  whether the'real_val' in line 105 should be 'real_test' and 'npz' in line 104 should be 'orm'? Thank you so much for your reply!
![2022-07-31 21-15-19 的屏幕截图](https://user-images.githubusercontent.com/103632128/182029069-80421ab1-4646-4490-80d0-e4754238e775.png)

**Comment by Ironman6666** [comment]
Here is the error info
![2022-07-31 21-07-12 的屏幕截图](https://user-images.githubusercontent.com/103632128/182029150-241608de-f65c-45db-9486-7f05197c629e.png)

**Comment by JiehongLin** [comment]
I‘m sorry for that. The code in Line225 should be added an input of ’subset‘:
` masks, coords, class_ids, instance_ids, model_list, bboxes, sizes = process_data(img_full_path, depth, subset='train')`

**Comment by Ironman6666** [comment]
> I‘m sorry for that. The code in Line225 should be added an input of ’subset‘: ` masks, coords, class_ids, instance_ids, model_list, bboxes, sizes = process_data(img_full_path, depth, subset='train')`
Thanks a lot!😊

**Comment by Ironman6666** [comment]
Sorry for bothering again.Whether the line 286 should be revised too?I have successully process the train data, it noticed me that"FileNotFoundError: [Errno 2] No such file or directory: '/obj_models/camera_val.pkl' 
![2022-08-01 14-02-14 的屏幕截图](https://user-images.githubusercontent.com/103632128/182083112-a9f12633-3d6e-41ba-884d-78fe547d8b04.png)
"

**Comment by Ironman6666** [comment]
There is a similar question in train.py. Whether there are other similar codes should be revised together?
![2022-08-03 19-04-03 的屏幕截图](https://user-images.githubusercontent.com/103632128/182593649-8518ad77-5873-4fe3-b3ce-22ca6dc31a95.png)
.

**Comment by ray8828** [comment]
I also miss the tge camera_val.pkl or real_test.pkl, can the author provide these files? thanks

**Comment by JiehongLin** [comment]
Sorry for that. I have uploaded those '*.pkl' files in the [link](https://drive.google.com/file/d/1Nz7cwcQWO_In4K6jKN1-5pQ0orY4UV9x/view?usp=sharing).

**Comment by Ironman6666** [comment]
"unsupervised_withMask.yaml" seems missed, How can I get it?

**Comment by Ironman6666** [comment]
And the log for unsupervised_withMask is also empty.How can I get the model?By the way,  is it convenient to release the training loss in different mode? I'm retraining the model in unsupervised mode with batchsize = 8 for 30 epoch, but the result model performs a large accuracy gap to  the best model.I train it with smaller lr for 5 epoch more, but the model seems already converged and the training loss stays arround 0.7. What should I do to reduce the gap,I has stucked here for long time and decided to take the liberty of asking for your opinion
![2022-08-18 09-53-24 的屏幕截图](https://user-images.githubusercontent.com/103632128/185275219-9e3fb1d3-df6a-4d52-84c3-3aa6fb7f50f4.png)
![2022-08-18 09-56-10 的屏幕截图](https://user-images.githubusercontent.com/103632128/185275872-c35b282b-1fc1-4409-bcc0-78f37cf787c2.png)
.

**Comment by YuxinCHENGPE** [comment]
> "unsupervised_withMask.yaml" seems missed, How can I get it? 

I also would like to try this config file, how can I get it? Thanks!

**Comment by JiehongLin** [comment]
> > "unsupervised_withMask.yaml" seems missed, How can I get it?
> 
> I also would like to try this config file, how can I get it? Thanks!

For this config, we jsut use gt masks to segment objects out for real training sets, instead of the masks predicted by maskrcnn..
