### ISSUE TITLE
Question: would any trained weights be provided?

### ISSUE THREAD

**Issue by Lynne-Zheng-Linfang** [JiehongLin/Self-DPDN#3]
Hi, thanks for sharing the code. Would you like to share the trained weights as well?

**Comment by JiehongLin** [comment]
Thanks for your attention on our work. The trained models could be download from the [Link](https://drive.google.com/file/d/1hWkbH4Z0RXQeYLxC_kOINxdTnDLtm9SX/view?usp=sharing).
