### ISSUE TITLE
How to calculate the mean shape?

### ISSUE THREAD

**Issue by JAISON96** [JiehongLin/Self-DPDN#8]
Hi, Thanks for the wonderful work. I was trying to do your method on a custom data. But I don't know how you calculated the mean shape of the object. Could you please provide the information on how to calculate the mean shape?

**Comment by JiehongLin** [comment]
We use the learned mean shapes provided by the paper of "Shape Prior Deformation for Categorical 6D Object Pose and Size Estimation".  You could refer to their [codes](https://github.com/mentian/object-deformnet/blob/master/mean_shape.py).
