### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/media/jian/ourdata/LHT/IST-NET/IST-Net-main/data/obj_models/camera_train.pkl'

### ISSUE THREAD

**Issue by SHN7x** [JiehongLin/Self-DPDN#9]
Where is the address obj_models/camera_train.pkl'

**Comment by JiehongLin** [comment]
For this file in our code, you can download from the [[link](https://drive.google.com/file/d/1Nz7cwcQWO_In4K6jKN1-5pQ0orY4UV9x/view?usp=drive_link)].

**Comment by 807448346** [comment]
> For this file in our code, you can download from the [[link](https://drive.google.com/file/d/1Nz7cwcQWO_In4K6jKN1-5pQ0orY4UV9x/view?usp=drive_link)].

thanks a lot！
